export const mockCategories = [
  { _id: 'cat_laptops', name: 'Laptops & Computers', slug: 'laptops-computers' },
  { _id: 'cat_cctv', name: 'CCTV & Security Systems', slug: 'cctv-security' },
  { _id: 'cat_printers', name: 'Printers & Copiers', slug: 'printers-copiers' },
  { _id: 'cat_networking', name: 'Networking & Wifi Router', slug: 'networking' },
  { _id: 'cat_accessories', name: 'Computer Accessories', slug: 'accessories' },
];

export const mockProducts = [
  {
    _id: '6a1ffcdf45924a9a6db023d8',
    name: 'Refurbished HP ProBook 440 G6',
    price: 24500,
    condition: 'used',
    description: 'Intel Core i5 8th Gen processor, 8GB DDR4 RAM, 256GB ultra-fast NVMe SSD, 14-inch HD Display, Windows 10 Pro pre-installed. Excellent cosmetic condition, fully checked and certified by our technicians. Includes 30 days shop warranty.',
    images: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1496181130204-7552cc14f1d0?auto=format&fit=crop&w=800&q=80',
    ],
    category: mockCategories[0],
    stock: 3,
    availability: true,
    featured: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    _id: '6a1ffcdf45924a9a6db023d9',
    name: 'Hikvision 4-Camera CCTV Security Kit',
    price: 15499,
    condition: 'new',
    description: 'Full HD 1080P Hikvision security system. Kit contains 2 Dome cameras (indoor), 2 Bullet cameras (outdoor weatherproof), 4-Channel Turbo HD DVR, 1TB Seagate Surveillance HDD, power supply adapters, and cables. Remote viewing setup included.',
    images: ['https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80'],
    category: mockCategories[1],
    stock: 5,
    availability: true,
    featured: true,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    _id: '6a1ffcdf45924a9a6db023da',
    name: 'Epson L3210 EcoTank InkTank Printer',
    price: 13200,
    condition: 'new',
    description: 'Brand new Epson EcoTank L3210 multi-function printer (Print, Scan, Copy). Spill-free, error-free ink refilling mechanism with high-yield ink bottles. Best for home and small business office needs. 1-year manufacturer warranty.',
    images: ['https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=800&q=80'],
    category: mockCategories[2],
    stock: 2,
    availability: true,
    featured: false,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    _id: '6a1ffcdf45924a9a6db023db',
    name: 'Used Dell 24-inch IPS Professional Monitor',
    price: 6500,
    condition: 'used',
    description: 'Dell Professional Series P2419H monitor. 24-inch Full HD (1920x1080) resolution with IPS technology for wide viewing angles. Ultra-thin bezel design, height-adjustable stand, pivot, tilt, swivel. Clean screen panel with minor body scuffs.',
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80'],
    category: mockCategories[0],
    stock: 4,
    availability: true,
    featured: false,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
];

export const mockSettings = {
  shopName: 'JAYAMBE INTEGRATORS',
  ownerName: 'Er. Anand',
  designation: 'EXTC ENGINEER',
  ownerPhoto: '/Anand.jpeg',
  email: 'anandp4994@gmail.com',
  phone: '+91 8879430925',
  whatsapp: '918879430925',
  address: 'Office: Mahavir Nagar, Shop No. 28, Navapur Road, Near to UCO Bank, Boisar (W).',
  workingHours: 'Monday - Saturday: 9:00 AM - 8:00 PM, Sunday: Closed',
  banners: [
    'https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1200&q=80',
  ],
  enableReviews: true,
};

export const mockGallery = [
  {
    _id: 'gal_1',
    title: 'CCTV Security Setup at Boisar Industrial Zone',
    description: 'Designed and deployed an 8-camera outdoor high-definition IP camera network with PoE switch and 4TB NVR for continuous 30-day recording. Remote viewing enabled on client mobile devices.',
    mediaUrl: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
    mediaType: 'image',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    _id: 'gal_2',
    title: 'Office Server Rack Cabinet Networking',
    description: 'Structured cabling, installation of Cat6 patch panels, Gigabit network switch configuration, and neat wire routing inside a 9U server rack cabinet for a corporate office client.',
    mediaUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    mediaType: 'image',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    _id: 'gal_3',
    title: 'High-End Gaming PC Build & Tuning',
    description: 'Custom assembly of Intel Core i9 processor, NVIDIA RTX GPU, liquid cooling radiator, and RGB fan routing. Stress-tested for peak thermal performance and framerate stability.',
    mediaUrl: 'https://images.unsplash.com/photo-1591405351990-4726e331f141?auto=format&fit=crop&w=800&q=80',
    mediaType: 'image',
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    _id: 'gal_4',
    title: 'Corporate Office Printer Fleet Setup',
    description: 'Deployed and networked five Epson EcoTank InkTank printers across departments. Configured print-over-wifi and scan-to-email options for all employee workstations.',
    mediaUrl: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=800&q=80',
    mediaType: 'image',
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
];
